type TEvents = {
    [key: string]: string
}

export let events: TEvents = {
    abort: 'abort',
    animationend: 'animationend',
    animationiteration: 'animationiteration',
    animationstart: 'animationstart',
    autocomplete: 'autocomplete',
    autocompleteerror: 'autocompleteerror',
    beforeunload: 'beforeunload',
    blur: 'blur',
    cancel: 'cancel',
    canplay: 'canplay',
    canplaythrough: 'canplaythrough',
    change: 'change',
    click: 'click',
    close: 'close',
    contextmenu: 'contextmenu',
    cuechange: 'cuechange',
    dblclick: 'dblclick',
    devicemotion: 'devicemotion',
    deviceorientation: 'deviceorientation',
    drag: 'drag',
    dragend: 'dragend',
    dragenter: 'dragenter',
    dragleave: 'dragleave',
    dragover: 'dragover',
    dragstart: 'dragstart',
    drop: 'drop',
    durationchange: 'durationchange',
    emptied: 'emptied',
    ended: 'ended',
    error: 'error',
    focus: 'focus',
    hashchange: 'hashchange',
    input: 'input',
    invalid: 'invalid',
    keydown: 'keydown',
    keypress: 'keypress',
    keyup: 'keyup',
    languagechange: 'languagechange',
    load: 'load',
    loadeddata: 'loadeddata',
    loadedmetadata: 'loadedmetadata',
    loadstart: 'loadstart',
    message: 'message',
    mousedown: 'mousedown',
    mouseenter: 'mouseenter',
    mouseleave: 'mouseleave',
    mousemove: 'mousemove',
    mouseout: 'mouseout',
    mouseover: 'mouseover',
    mouseup: 'mouseup',
    mousewheel: 'mousewheel',
    offline: 'offline',
    line: 'line',
    pagehide: 'pagehide',
    pageshow: 'pageshow',
    pause: 'pause',
    play: 'play',
    playing: 'playing',
    popstate: 'popstate',
    progress: 'progress',
    ratechange: 'ratechange',
    rejectionhandled: 'rejectionhandled',
    reset: 'reset',
    resize: 'resize',
    scroll: 'scroll',
    search: 'search',
    seeked: 'seeked',
    seeking: 'seeking',
    select: 'select',
    show: 'show',
    stalled: 'stalled',
    storage: 'storage',
    submit: 'submit',
    suspend: 'suspend',
    timeupdate: 'timeupdate',
    toggle: 'toggle',
    transitionend: 'transitionend',
    unhandledrejection: 'unhandledrejection',
    unload: 'unload',
    volumechange: 'volumechange',
    waiting: 'waiting',
    webkitanimationend: 'webkitanimationend',
    webkitanimationiteration: 'webkitanimationiteration',
    webkitanimationstart: 'webkitanimationstart',
    webkittransitionend: 'webkittransitionend',
    wheel: 'wheel'
}

export function addEvent(name: string, value: string) {
    events[name] = value;
}